// Generated by Xata Codegen 0.29.5. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "guest_signs",
    columns: [
      { name: "author", type: "string" },
      { name: "message", type: "string" },
      { name: "approved", type: "bool", notNull: true, defaultValue: "false" },
      { name: "user_email", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type GuestSigns = InferredTypes["guest_signs"];
export type GuestSignsRecord = GuestSigns & XataRecord;

export type DatabaseSchema = {
  guest_signs: GuestSignsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL: process.env.XATA_URL,
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
